export const styles = {
  logo: {
    flexGrow: 1,
    fontFamily: 'Reem Kufi Ink',
    fontWeight: 'bold',
    color: 'secondary.main',
  },
  cartButton: {
    px: '50px',
    borderRadius: '20px',
    color: 'pink.main',
    fontWeight: 'bold',
  },
  mealsList: {
    width: '1200px',
    border: '4px solid #FA7070',
    borderRadius: '15px',
    padding: '30px',
    margin: '50px auto 0',
    backgroundColor: 'secondary.main',
  },
  cartModal: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: 400,
    bgcolor: 'secondary.main',
    border: '4px solid #FA7070',
    borderRadius: '15px',
    padding: '30px',
  },
  bannerCard: {
    width: '600px',
    position: 'absolute',
    top: '50%',
    left: '50%',
    color: 'secondary.main',
    transform: 'translate(-50%, -50%)',
    backgroundColor: 'primary.main',
    padding: '20px',
    borderRadius: '20px',
    textAlign: 'center',
    boxShadow: '0px 5px 15px 4px rgba(0,0,0,0.5)',
  },
};
